
--------------------begin------------------------

[2020/01/14 09:28:10.367537][i][4c0a16fd8] recv loop terminated: err=failed to read from connection: read tcp 192.168.5.62:48926->192.168.0.101:2181: i/o timeout
[2020/01/14 09:28:10.367558][i][4c0a16fd8] send loop terminated: err=<nil>
[2020/01/14 09:28:10.367649][w][4c0a16fd8] zk已断开连接:[192.168.0.101]
[2020/01/14 09:28:12.367984][i][4c0a16fd8] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2020/01/14 09:28:14.368361][i][4c0a16fd8] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2020/01/14 09:28:16.368697][i][4c0a16fd8] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2020/01/14 09:28:18.368968][i][4c0a16fd8] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2020/01/14 09:28:20.369329][i][4c0a16fd8] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2020/01/14 09:28:22.369711][i][4c0a16fd8] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2020/01/14 09:28:24.370294][i][4c0a16fd8] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2020/01/14 09:28:26.370663][i][4c0a16fd8] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2020/01/14 09:28:28.371108][i][4c0a16fd8] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2020/01/14 09:28:30.371486][i][4c0a16fd8] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2020/01/14 09:28:32.371937][i][4c0a16fd8] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2020/01/14 09:28:34.372239][i][4c0a16fd8] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2020/01/14 09:28:36.372718][i][4c0a16fd8] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2020/01/14 09:28:38.372911][i][4c0a16fd8] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2020/01/14 09:28:40.373246][i][4c0a16fd8] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2020/01/14 09:28:42.373816][i][4c0a16fd8] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2020/01/14 09:28:43.659407][i][4c0a16fd8] Connected to 192.168.0.101:2181
[2020/01/14 09:28:44.303911][i][4c0a16fd8] authentication failed: zk: session has been expired by the server
[2020/01/14 09:28:44.303933][w][4c0a16fd8] zk已断开连接:[192.168.0.101]
[2020/01/14 09:28:45.304524][i][4c0a16fd8] Connected to 192.168.0.101:2181
[2020/01/14 09:28:45.316980][i][4c0a16fd8] authenticated: id=103116747297990146, timeout=4000
[2020/01/14 09:28:45.316995][i][4c0a16fd8] re-submitting `0` credentials after reconnect
[2020/01/14 09:28:46.310659][i][920db0212] 开始启动[API]服务...
[2020/01/14 09:28:46.310752][e][920db0212] 启动失败 创建db失败:{
  "provider": "mysql",
  "connString": "oms_t:123456@tcp(192.168.0.36)/oms_t?charset=utf8",
  "maxOpen": 20,
  "maxIdle": 10,
  "lifeTime": 600
},err:sql: unknown driver "mysql" (forgotten import?)

---------------------end-------------------------

--------------------begin------------------------

[2020/01/14 14:02:09.13675][i][4c0a16fd8] recv loop terminated: err=failed to read from connection: read tcp 192.168.5.62:34244->192.168.0.101:2181: i/o timeout
[2020/01/14 14:02:09.13715][i][4c0a16fd8] send loop terminated: err=<nil>
[2020/01/14 14:02:09.13812][w][4c0a16fd8] zk已断开连接:[192.168.0.101]
[2020/01/14 14:02:11.14209][i][4c0a16fd8] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2020/01/14 14:02:13.14626][i][4c0a16fd8] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2020/01/14 14:02:15.15024][i][4c0a16fd8] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2020/01/14 14:02:17.15237][i][4c0a16fd8] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2020/01/14 14:02:19.15590][i][4c0a16fd8] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2020/01/14 14:02:21.16050][i][4c0a16fd8] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2020/01/14 14:02:23.16460][i][4c0a16fd8] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2020/01/14 14:02:25.16969][i][4c0a16fd8] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2020/01/14 14:02:27.17389][i][4c0a16fd8] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2020/01/14 14:02:29.17797][i][4c0a16fd8] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2020/01/14 14:02:31.18159][i][4c0a16fd8] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2020/01/14 14:02:33.18682][i][4c0a16fd8] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2020/01/14 14:02:35.19214][i][4c0a16fd8] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2020/01/14 14:02:37.19620][i][4c0a16fd8] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2020/01/14 14:02:39.19987][i][4c0a16fd8] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2020/01/14 14:02:41.20452][i][4c0a16fd8] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2020/01/14 14:02:43.20920][i][4c0a16fd8] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2020/01/14 14:02:44.21251][i][4c0a16fd8] Connected to 192.168.0.101:2181
[2020/01/14 14:02:44.22356][i][4c0a16fd8] authentication failed: zk: session has been expired by the server
[2020/01/14 14:02:44.22366][w][4c0a16fd8] zk已断开连接:[192.168.0.101]
[2020/01/14 14:02:45.23250][i][4c0a16fd8] Connected to 192.168.0.101:2181
[2020/01/14 14:02:45.33915][i][4c0a16fd8] authenticated: id=103116747297990212, timeout=4000
[2020/01/14 14:02:45.33931][i][4c0a16fd8] re-submitting `0` credentials after reconnect
[2020/01/14 14:02:46.54593][i][0711c268d] 开始启动[API]服务...
[2020/01/14 14:02:46.54699][e][0711c268d] 启动失败 创建db失败:{
  "provider": "mysql",
  "connString": "oms_t:123456@tcp(192.168.0.36)/oms_t?charset=utf8",
  "maxOpen": 20,
  "maxIdle": 10,
  "lifeTime": 600
},err:sql: unknown driver "mysql" (forgotten import?)

---------------------end-------------------------
