
--------------------begin------------------------

[2020/01/19 09:29:38.628698][i][4c0a16fd8] recv loop terminated: err=failed to read from connection: read tcp 192.168.5.62:59944->192.168.0.101:2181: i/o timeout
[2020/01/19 09:29:38.628731][i][4c0a16fd8] send loop terminated: err=<nil>
[2020/01/19 09:29:38.628856][w][4c0a16fd8] zk已断开连接:[192.168.0.101]
[2020/01/19 09:29:40.629117][i][4c0a16fd8] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2020/01/19 09:29:42.629357][i][4c0a16fd8] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2020/01/19 09:29:44.629818][i][4c0a16fd8] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2020/01/19 09:29:46.633864][i][4c0a16fd8] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2020/01/19 09:29:48.634344][i][4c0a16fd8] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2020/01/19 09:29:50.634769][i][4c0a16fd8] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2020/01/19 09:29:52.635196][i][4c0a16fd8] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2020/01/19 09:29:54.635687][i][4c0a16fd8] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2020/01/19 09:29:56.636068][i][4c0a16fd8] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2020/01/19 09:29:58.636419][i][4c0a16fd8] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2020/01/19 09:30:00.636921][i][4c0a16fd8] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2020/01/19 09:30:02.637407][i][4c0a16fd8] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2020/01/19 09:30:04.637729][i][4c0a16fd8] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2020/01/19 09:30:06.638070][i][4c0a16fd8] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2020/01/19 09:30:07.779538][i][4c0a16fd8] Connected to 192.168.0.101:2181
[2020/01/19 09:30:07.781399][i][4c0a16fd8] authentication failed: zk: session has been expired by the server
[2020/01/19 09:30:07.781578][w][4c0a16fd8] zk已断开连接:[192.168.0.101]
[2020/01/19 09:30:08.782501][i][4c0a16fd8] Connected to 192.168.0.101:2181
[2020/01/19 09:30:08.799782][i][4c0a16fd8] authenticated: id=103116747297991548, timeout=4000
[2020/01/19 09:30:08.799800][i][4c0a16fd8] re-submitting `0` credentials after reconnect
[2020/01/19 09:30:09.829529][i][3d8d5a418] 开始启动[API]服务...
[2020/01/19 09:30:09.829866][e][3d8d5a418] 启动失败 创建db失败:{
  "provider": "mysql",
  "connString": "oms_t:123456@tcp(192.168.0.36)/oms_t?charset=utf8",
  "maxOpen": 20,
  "maxIdle": 10,
  "lifeTime": 600
},err:sql: unknown driver "mysql" (forgotten import?)

---------------------end-------------------------

--------------------begin------------------------

[2020/01/19 10:15:11.100736][i][1c12c9965] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: connect: no route to host
[2020/01/19 10:15:13.101042][i][1c12c9965] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2020/01/19 10:15:14.332751][i][1c12c9965] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: connect: no route to host
[2020/01/19 10:15:16.333449][i][1c12c9965] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2020/01/19 10:15:18.333894][i][1c12c9965] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2020/01/19 10:15:20.334121][i][1c12c9965] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2020/01/19 10:15:21.468515][i][1c12c9965] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: connect: no route to host
[2020/01/19 10:15:23.468878][i][1c12c9965] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2020/01/19 10:15:24.822149][i][1c12c9965] Connected to 192.168.0.101:2181
[2020/01/19 10:15:24.834179][i][1c12c9965] authenticated: id=103116747297991562, timeout=4000
[2020/01/19 10:15:24.834185][i][1c12c9965] re-submitting `0` credentials after reconnect
[2020/01/19 10:15:24.870667][i][1c12c9965] 初始化 /oms_t_debug/omsadmin/api/5.62
[2020/01/19 10:15:26.61234][i][038d34e86] 开始启动[API]服务...
[2020/01/19 10:15:26.61346][e][038d34e86] 启动失败 创建db失败:{
  "provider": "mysql",
  "connString": "oms_t:123456@tcp(192.168.0.36)/oms_t?charset=utf8",
  "maxOpen": 20,
  "maxIdle": 10,
  "lifeTime": 600
},err:sql: unknown driver "mysql" (forgotten import?)

---------------------end-------------------------
